server:
  port: 8082

info:
  app:
    name: Servicio consumidor
    description: Este es un servicio de consumidor, que consumira el cliente registrado en Eureka
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    env:
      enabled: true

spring:
  application:
    name: servicio-consumidor

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/